// app.js - logica minima per COMPRAMI
const ADMIN_EMAIL="FischerStephane1@gmail.com";
const PRODUCTS=[
{id:"p1",title:"Prodotto 1",description:"Descrizione prodotto 1",image:"https://picsum.photos/seed/p1/640/400",ownerEmail:ADMIN_EMAIL},
{id:"p2",title:"Prodotto 2",description:"Descrizione prodotto 2",image:"https://picsum.photos/seed/p2/640/400",ownerEmail:ADMIN_EMAIL},
{id:"p3",title:"Prodotto 3",description:"Descrizione prodotto 3",image:"https://picsum.photos/seed/p3/640/400",ownerEmail:ADMIN_EMAIL},
{id:"p4",title:"Prodotto 4",description:"Descrizione prodotto 4",image:"https://picsum.photos/seed/p4/640/400",ownerEmail:ADMIN_EMAIL}
];
function saveSession(user){localStorage.setItem("comprami_user",JSON.stringify(user));}
function getSession(){const s=localStorage.getItem("comprami_user");return s?JSON.parse(s):null;}
function logout(){localStorage.removeItem("comprami_user");window.location.href="index.html";}
function checkAuth(redirect="index.html"){const user=getSession();if(!user){localStorage.setItem("after_login",window.location.pathname);window.location.href=redirect;return false;}return true;}
function initIndex(){const loginForm=document.getElementById("loginForm");const regForm=document.getElementById("regForm");if(loginForm){loginForm.addEventListener("submit",(e)=>{e.preventDefault();const email=document.getElementById("login_email").value.trim();const username=document.getElementById("login_username").value.trim();if(!email||!username){alert("Compila tutti i campi");return;}saveSession({email,username,photo:"https://i.pravatar.cc/150?u="+email,phone:"",position:""});const after=localStorage.getItem("after_login")||"home.html";window.location.href=after;});}
if(regForm){regForm.addEventListener("submit",(e)=>{e.preventDefault();const email=document.getElementById("reg_email").value.trim();const username=document.getElementById("reg_username").value.trim();if(!email||!username){alert("Compila tutti i campi");return;}saveSession({email,username,photo:"https://i.pravatar.cc/150?u="+email,phone:"",position:""});const body=encodeURIComponent(`Nuova registrazione:\nEmail:${email}\nUsername:${username}`);window.open(`mailto:${ADMIN_EMAIL}?subject=Nuova registrazione COMPRAMI&body=${body}`);const after=localStorage.getItem("after_login")||"home.html";window.location.href=after;});}}
function initHome(){if(!checkAuth())return;const user=getSession();document.getElementById("welcome").innerText=`Benvenuto, ${user.username}`;const grid=document.getElementById("productsGrid");for(const p of PRODUCTS){const div=document.createElement("div");div.className="card product-thumb";div.innerHTML=`<img src="${p.image}" alt="${p.title}"><h3>${p.title}</h3><p class="meta">${p.description}</p><div class="actions"><a class="small-btn" href="prodotto${p.id.slice(1)}.html">Vedi</a></div>`;grid.appendChild(div);}
const profiles=document.getElementById("profilesGrid");const owner={email:ADMIN_EMAIL,username:"VenditoreUfficiale",position:"Italia",photo:"https://i.pravatar.cc/100?u=venditore"};const card=document.createElement("div");card.className="card";card.innerHTML=`<div class="profile-mini"><img src="${owner.photo}" alt="venditore"><div><div style="font-weight:700">${owner.username}</div><div class="meta">${owner.position}</div><div class="note">${owner.email}</div><div class="actions"><a class="small-btn" href="profilo.html">Vedi profilo</a></div></div></div>`;profiles.appendChild(card);}
function initProduct(id){if(!checkAuth())return;const p=PRODUCTS.find(x=>x.id===id);if(!p){document.getElementById("productArea").innerHTML="<div class='card'>Prodotto non trovato</div>";return;}const html=`<div class="card"><img src="${p.image}" style="width:100%;height:320px;object-fit:cover;border-radius:6px"><h2>${p.title}</h2><p class="meta">${p.description}</p><p class="note">Contatta il proprietario per discutere privatamente.</p><div class="actions"><a class="small-btn" href="mailto:${p.ownerEmail}?subject=Interesse prodotto ${encodeURIComponent(p.title)}">Invia email al venditore</a></div></div>`;document.getElementById("productArea").innerHTML=html;}
function initProfile(){if(!checkAuth())return;const user=getSession();const html=`<div class="card"><div style="display:flex;gap:14px;align-items:center"><img src="${user.photo}" style="width:120px;height:120px;border-radius:12px;object-fit:cover"><div><h2>${user.username}</h2><div class="meta">${user.email}</div><div class="meta">Posizione: Italia</div></div></div><div class="actions"><button class="btn" id="payBtn">PAGARE ORA</button><button class="btn" id="refundBtn" style="background:#333">RICHIEDI RIMBORSO</button></div><p class="note">L'azienda valuterà la richiesta e sarà l'unica a autorizzare il rimborso.</p></div>`;document.getElementById("profileArea").innerHTML=html;document.getElementById("payBtn").addEventListener("click",()=>{const PAYPAL_LINK="https://paypal.me/COMPRAMI";window.open(PAYPAL_LINK,"_blank");});document.getElementById("refundBtn").addEventListener("click",()=>{const subject=encodeURIComponent("Richiesta rimborso - COMPRAMI");const body=encodeURIComponent(`Richiesta rimborso\nUtente:${user.username}\nEmail:${user.email}\nDettagli:`);window.open(`mailto:${ADMIN_EMAIL}?subject=${subject}&body=${body}`);});}
document.addEventListener("DOMContentLoaded",()=>{const page=document.body.getAttribute("data-page");if(page==="index")initIndex();if(page==="home")initHome();if(page==="prodotto1")initProduct("p1");if(page==="prodotto2")initProduct("p2");if(page==="prodotto3")initProduct("p3");if(page==="prodotto4")initProduct("p4");if(page==="profilo")initProfile();const lo=document.getElementById("logoutBtn");if(lo)lo.addEventListener("click",logout);});
